name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python_version: ['3.5', '3.6', '3.7', '3.8']

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker build . --build-arg PYTHON_VERSION=${{ matrix.python_version }} --file Dockerfile --tag optuna-sample:$(date +%s)-${{ matrix.python_version }}
